### ISSUE TITLE
3.1.4 world loading crash

### ISSUE THREAD

**Issue by VaporeonScripts** [InvictusSlayer/Slayers-Beasts#10]
after using 3.1.4, the client doesnt crash anymore upon clicking make world, but at exactly 12% of process of making a world, it completely freezes.

**Comment by InvictusSlayer** [comment]
Log file please!!

**Comment by InvictusSlayer** [comment]
I've checked through the mods from the previous crash report and unless you've added more mods since it's a compatibility problem with Nature Arise which I'll sort out asap

**Comment by VaporeonScripts** [comment]
Unable to send the log file because feather freezes too when it freezes mc and i alt f4

**Comment by VaporeonScripts** [comment]
I will try get the log file asap

**Comment by VaporeonScripts** [comment]
I will try removing nature arise and use ur mod and see how it goes
