### ISSUE TITLE
Missing element ResourceKey[minecraft:worldgen/noise / slayersbeasts:mixed_sand_layer]

### ISSUE THREAD

**Issue by lupiiiin** [InvictusSlayer/Slayers-Beasts#14]
Version (slayersbeasts-fabric-1.20.1-1.3.0)

When entering the Sepulchra dimension, the server crashes. I share the crash.

https://pastebin.com/Z3KzVDXy

**Comment by InvictusSlayer** [comment]
The sepulchra dimension was deprecated many versions ago, which is why it can't be generated without command. I may yet reintroduce it but there are no plans for the forseeable future.

**Comment by lupiiiin** [comment]
Thank you very much for replying!
