### ISSUE TITLE
Compatibility issue with Wyther's Ecosphere and Terrestria

### ISSUE THREAD

**Issue by Dumpling00** [InvictusSlayer/Slayers-Beasts#5]
Hey there - sorry again but I'm trying this in conjunction with other biome enhancing mods and there seems to be issues with Terrestria (maybe as a whole) and one specific biome in Wyther's Ecosphere. Here's the crash report for both, not sure if anything can be done.

Thank you for your patience and dedication!
[crash-2024-03-17_02.47.30-server.txt](https://github.com/InvictusSlayer/Slayers-Beasts/files/14628840/crash-2024-03-17_02.47.30-server.txt)
[crash-2024-03-17_03.27.09-server.txt](https://github.com/InvictusSlayer/Slayers-Beasts/files/14628843/crash-2024-03-17_03.27.09-server.txt)

**Comment by InvictusSlayer** [comment]
Thanks for bringing this to my attention! These feature order cycle issues are easy to fix, it's just a bit tedious to go through and find all the biomes that it's a problem for. I've found the culprits in this case but, before I make a new patch, have you found any other biomes that share this issue?

**Comment by Dumpling00** [comment]
Hard to say! The thing is, the mod seems to launch fine, it's only when entering proximity with specific biomes that the crash happens.

**Comment by InvictusSlayer** [comment]
Well let's hope this is the last one. It was the same feature for both those crashes
