### ISSUE TITLE
Guess who's back, back again

### ISSUE THREAD

**Issue by Dumpling00** [InvictusSlayer/Slayers-Beasts#7]
Hello! Okay so, this time things are a bit different.

Mod seems to work (not sure if there will be biome-specific crashes depending on proximity).

Tested compatibility with Terrestria - All seems fine!
Tested compatibility with Traverse - All seems fine!
Tested compatibility with William's Ecosphere - All seems fine!
Tested compatibility with William's Overhaul - All seems fine!

But now... there's this other issue with another mod. "Fish of Thieves". I already had this installed, prior to adding this new version of slayer's. The game outright refuses to launch.

Here's the crash report- this time it seems to just be about entities and not biomes, but I'm no expert haha
Says Registry object not present: slayersbeasts:white_mushroom

[crash-2024-03-20_23.05.22-client.txt](https://github.com/InvictusSlayer/Slayers-Beasts/files/14675537/crash-2024-03-20_23.05.22-client.txt)

Keep rocking!

**Comment by InvictusSlayer** [comment]
I briefly checked through this a couple days ago and the error here will not be trivial to solve. Since it's the Easter holidays I'll be quite busy with family and revision for exams for then next couple months, but I'll try to crack this slowly when I can make time!!

**Comment by InvictusSlayer** [comment]
Okay I think I've figured out what this is caused by so it should be solved in the next update
